nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://192.168.1.35:4200']
        allow_headers: ['content-type', 'authorization']
        expose_headers: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/': null
